---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: expressjs-k8s
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.3
spec:
  chart:
  chart:
    git: https://github.com/shantanuyelwande/expressjs-k8s
    path: chart/expressjs-k8s
    ref: master
  values:
    ingress:
      enabled: false
    image: shantanuy/expressjs-k8s-service:0.0.1
